### ISSUE TITLE
What is the goal of this project?

### ISSUE THREAD

**Issue by KittenBall** [Erlanglin/accountbooks#1]
Sorry to ask this question，but I'm curious what the project really wants to achieve ,and what the significance of this project is?

**Comment by Erlanglin** [comment]
It makes sense after doing it，You are a chicken, you do not understand my thought.You can call me "dashuaige"(means of 大帅哥).

**Comment by KittenBall** [comment]
Oh，you're so damn shameless that I can't stand it and stop replying me
